export type Tinstitution =
  | "PlanetCash"
  | "PlanetBPS"
  | "BS Milicz"
  | "PlanetBNPP"
  | "mBank"
  | "ING"
  | "SGB SA"
  | "BS Kobierzyce"
  | "PlanetING"
  | "NCRO"
  | "CreditAgricole";

export type Tmodules = "cashout" | "cashinout";
export interface IatmElement {
  id: number;
  nazwa: string;
  nazwaLokalizacji: string;
  adresLokalizacji: string;
  instytucja: Tinstitution;
  moduly: Tmodules;
  konfiguracje: string[] | [];
  typWplaty: string;
  lokalizacja: string;
  lat: number;
  lng: number;
}

export const atmsDummyData: IatmElement[] = [
  {
    id: 0,
    nazwa: "PNET1261",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Szybka 2/4, 50-421 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Szybka 2/4, 50-421 Wrocław",
    lat: 51.1024,
    lng: 17.053,
  },
  {
    id: 1,
    nazwa: "PNET1350",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Komandorska 147, 53-344 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "46886",
    lokalizacja: "Biedronka, Komandorska 147, 53-344 Wrocław",
    lat: 51.0931,
    lng: 17.0254,
  },
  {
    id: 2,
    nazwa: "PNET1355",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Grabarska 2, 50-079 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Grabarska 2, 50-079 Wrocław",
    lat: 51.110756,
    lng: 17.025127,
  },
  {
    id: 3,
    nazwa: "PNET1389",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Rogowska 119, 54-440 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Rogowska 119, 54-440 Wrocław",
    lat: 51.1176,
    lng: 16.946,
  },
  {
    id: 4,
    nazwa: "PNET1562",
    nazwaLokalizacji: "Millenium Tower",
    adresLokalizacji: "Strzegomska 42a, 53-611 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Millenium Tower, Strzegomska 42a, 53-611 Wrocław",
    lat: 51.11368112,
    lng: 16.9957904,
  },
  {
    id: 5,
    nazwa: "PNET1607",
    nazwaLokalizacji: "Lewiatan",
    adresLokalizacji: "Borowska 214, 50-588 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "49138",
    lokalizacja: "Lewiatan, Borowska 214, 50-588 Wrocław",
    lat: 51.09074251,
    lng: 17.03306511,
  },
  {
    id: 6,
    nazwa: "PNET1621",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Krynicka 1, 50-555 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "49261",
    lokalizacja: "Biedronka, Krynicka 1, 50-555 Wrocław",
    lat: 51.082612,
    lng: 17.046473,
  },
  {
    id: 7,
    nazwa: "PNET1665",
    nazwaLokalizacji: "Sklep Spożywczy Biedronka PK",
    adresLokalizacji: "Św.Jerzego 2, 50-518 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "49582",
    lokalizacja: "Sklep Spożywczy Biedronka PK, Św.Jerzego 2, 50-518 Wrocław",
    lat: 51.087428,
    lng: 17.045406,
  },
  {
    id: 8,
    nazwa: "PNET1707",
    nazwaLokalizacji: "przy Żabce",
    adresLokalizacji: "Gajowicka 177, 53-150 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "przy Żabce, Gajowicka 177, 53-150 Wrocław",
    lat: 51.08551,
    lng: 17.004099,
  },
  {
    id: 9,
    nazwa: "RNET2240",
    nazwaLokalizacji: "Stacja Paliw Bisek ",
    adresLokalizacji: "Przybyły 20, 54-512 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "378600",
    lokalizacja: "Stacja Paliw Bisek , Przybyły 20, 54-512 Wrocław",
    lat: 51.117718,
    lng: 16.916199,
  },
  {
    id: 10,
    nazwa: "PNET2301",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Wróblewskiego 7, 51-627 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "53824",
    lokalizacja: "Biedronka, Wróblewskiego 7, 51-627 Wrocław",
    lat: 51.10438623,
    lng: 17.08079611,
  },
  {
    id: 11,
    nazwa: "PNET8235",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Powstańców Śląskich 159, 53-139 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Powstańców Śląskich 159, 53-139 Wrocław",
    lat: 51.0871224,
    lng: 17.0122779,
  },
  {
    id: 12,
    nazwa: "PNET8306",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Trzmielowicka 7/9, 54-002 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Trzmielowicka 7/9, 54-002 Wrocław",
    lat: 51.1452,
    lng: 16.8655,
  },
  {
    id: 13,
    nazwa: "PNET9401",
    nazwaLokalizacji: "Społem",
    adresLokalizacji: "Jemiołowa 50/54, 53-447 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Społem, Jemiołowa 50/54, 53-447 Wrocław",
    lat: 51.09567031,
    lng: 17.00844847,
  },
  {
    id: 14,
    nazwa: "PNET9892",
    nazwaLokalizacji: "Sklep",
    adresLokalizacji: "pl. Grunwaldzki 30, 50-357 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "57742",
    lokalizacja: "Sklep, pl. Grunwaldzki 30, 50-357 Wrocław",
    lat: 51.11416774,
    lng: 17.06661418,
  },
  {
    id: 15,
    nazwa: "PNET9902",
    nazwaLokalizacji: "CH Carrefour",
    adresLokalizacji: "Bardzka 3, 50-516 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "57750",
    lokalizacja: "CH Carrefour, Bardzka 3, 50-516 Wrocław",
    lat: 51.0819861,
    lng: 17.048614,
  },
  {
    id: 16,
    nazwa: "PNETB017",
    nazwaLokalizacji: "BPS",
    adresLokalizacji: "Kurzy Targ 5, 50-102 Wrocław",
    instytucja: "PlanetBPS",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "58138",
    lokalizacja: "BPS, Kurzy Targ 5, 50-102 Wrocław",
    lat: 51.10955936,
    lng: 17.03374958,
  },
  {
    id: 17,
    nazwa: "PNETB019",
    nazwaLokalizacji: "BPS",
    adresLokalizacji: "Sienkiewicza 77, 50-348 Wrocław",
    instytucja: "PlanetBPS",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "BPS, Sienkiewicza 77, 50-348 Wrocław",
    lat: 51.11593529,
    lng: 17.05829799,
  },
  {
    id: 18,
    nazwa: "BPSA2950",
    nazwaLokalizacji: "Bank",
    adresLokalizacji: "Kamienna 115, 50-545 Wrocław",
    instytucja: "BS Milicz",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "83045",
    lokalizacja: "Bank, Kamienna 115, 50-545 Wrocław",
    lat: 51.087367,
    lng: 17.040711,
  },
  {
    id: 19,
    nazwa: "RNET5E52",
    nazwaLokalizacji: "CH Carrefour/CH Borek",
    adresLokalizacji: "Hallera 52, 50-984 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "50615",
    lokalizacja: "CH Carrefour/CH Borek, Hallera 52, 50-984 Wrocław",
    lat: 51.08852778,
    lng: 16.99908333,
  },
  {
    id: 20,
    nazwa: "RNET2430",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Wilanowska 25, 51-206 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "45236",
    lokalizacja: "Biedronka, Wilanowska 25, 51-206 Wrocław",
    lat: 51.1556,
    lng: 17.1322,
  },
  {
    id: 21,
    nazwa: "RNET5E39",
    nazwaLokalizacji: "Renoma",
    adresLokalizacji: "Świdnicka 40, 50-027 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "",
    lokalizacja: "Renoma, Świdnicka 40, 50-027 Wrocław",
    lat: 51.103744,
    lng: 17.030802,
  },
  {
    id: 22,
    nazwa: "RNET5F07",
    nazwaLokalizacji: "Arkady Wrocławskie ",
    adresLokalizacji: "Powstańców Śląskich 2-4, 53-333 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "",
    lokalizacja: "Powstańców Śląskich 2-4, 53-333 Wrocław",
    lat: 51.09944,
    lng: 17.029403,
  },
  {
    id: 23,
    nazwa: "RNET6592",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Swobodna 3, 50-541 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "",
    lokalizacja: "Swobodna 3, 50-541 Wrocław",
    lat: 51.0981891,
    lng: 17.0323355,
  },
  {
    id: 24,
    nazwa: "RNET5F33",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Lotnicza 24, 54-155 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "",
    lokalizacja: "Biedronka, Lotnicza 24, 54-155 Wrocław",
    lat: 51.1291,
    lng: 16.9708,
  },
  {
    id: 25,
    nazwa: "RNET2534",
    nazwaLokalizacji: "Galeria Wroclavia",
    adresLokalizacji: "Sucha 1, 50-086 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "305745",
    lokalizacja: "Galeria Wroclavia, Sucha 1, 50-086 Wrocław",
    lat: 51.096853,
    lng: 17.03414,
  },
  {
    id: 26,
    nazwa: "RNET2535",
    nazwaLokalizacji: "Galeria Wroclavia",
    adresLokalizacji: "Sucha 1, 50-086 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "305745",
    lokalizacja: "Galeria Wroclavia, Sucha 1, 50-086 Wrocław",
    lat: 51.096853,
    lng: 17.03414,
  },
  {
    id: 27,
    nazwa: "RNET2711",
    nazwaLokalizacji: "Auchan",
    adresLokalizacji: "Zwycięska 14A-14B, 53-033 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "50193",
    lokalizacja: "Auchan, Zwycięska 14A-14B, 53-033 Wrocław",
    lat: 51.0592,
    lng: 17.0086,
  },
  {
    id: 28,
    nazwa: "RNET2712",
    nazwaLokalizacji: "Galeria Wroclavia",
    adresLokalizacji: "Sucha 1, 50-086 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "305745",
    lokalizacja: "Galeria Wroclavia, Sucha 1, 50-086 Wrocław",
    lat: 51.096853,
    lng: 17.03414,
  },
  {
    id: 29,
    nazwa: "PNET2909",
    nazwaLokalizacji: "Port Lotniczy",
    adresLokalizacji: "Graniczna 190, 54-530 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Port Lotniczy, Graniczna 190, 54-530 Wrocław",
    lat: 51.104002,
    lng: 16.880856,
  },
  {
    id: 30,
    nazwa: "RNET2927",
    nazwaLokalizacji: "CH Tarasy Grabiszyńskie ",
    adresLokalizacji: "Grabiszyńska 240, 50-001 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "CH Tarasy Grabiszyńskie , Grabiszyńska 240, 50-001 Wrocław",
    lat: 51.094257,
    lng: 16.98151,
  },
  {
    id: 31,
    nazwa: "RNET2557",
    nazwaLokalizacji: "Pasaż Grunwaldzki",
    adresLokalizacji: "Pl. Grunwaldzki 22, 50-363 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "60622",
    lokalizacja: "Pasaż Grunwaldzki, Pl. Grunwaldzki 22, 50-363 Wrocław",
    lat: 51.11331404,
    lng: 17.05975845,
  },
  {
    id: 32,
    nazwa: "RNET2511",
    nazwaLokalizacji: "Pasaż Grunwaldzki",
    adresLokalizacji: "Pl. Grunwaldzki 22, 50-363 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "60622",
    lokalizacja: "Pasaż Grunwaldzki, Pl. Grunwaldzki 22, 50-363 Wrocław",
    lat: 51.11331404,
    lng: 17.05975845,
  },
  {
    id: 33,
    nazwa: "PNET1947",
    nazwaLokalizacji: "N-Park ",
    adresLokalizacji: "Gagarina 27, 54-620 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "N-Park , Gagarina 27, 54-620 Wrocław",
    lat: 51.094702,
    lng: 16.933457,
  },
  {
    id: 34,
    nazwa: "RNET5C08",
    nazwaLokalizacji: "mKiosk w CH Borek",
    adresLokalizacji: "Hallera 52, 50-984 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "393469",
    lokalizacja: "mKiosk w CH Borek, Hallera 52, 50-984 Wrocław",
    lat: 51.088631,
    lng: 16.998189,
  },
  {
    id: 35,
    nazwa: "RNET6704",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Krawiecka 1F, 50-148 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "66743",
    lokalizacja: "BNP Paribas, Krawiecka 1F, 50-148 Wrocław",
    lat: 51.10884827,
    lng: 17.03820422,
  },
  {
    id: 36,
    nazwa: "RNET7107",
    nazwaLokalizacji: "Oddział ING",
    adresLokalizacji: "Szewska 72, 50-121 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "Oddział ING, Szewska 72, 50-121 Wrocław",
    lat: 51.110177,
    lng: 17.034322,
  },
  {
    id: 37,
    nazwa: "RNETP005",
    nazwaLokalizacji: "Oddział ING",
    adresLokalizacji: "Szewska 72, 50-121 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "Oddział ING, Szewska 72, 50-121 Wrocław",
    lat: 51.110177,
    lng: 17.034322,
  },
  {
    id: 38,
    nazwa: "RNET6774",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Pl. Grunwaldzki 23, 50-365 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "Disabled",
    lokalizacja: "BNP Paribas, Pl. Grunwaldzki 23, 50-365 Wrocław",
    lat: 51.1122954,
    lng: 17.0625485,
  },
  {
    id: 39,
    nazwa: "RNET5C32",
    nazwaLokalizacji: "CH Korona",
    adresLokalizacji: "Krzywoustego 126, 51-421 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "Disabled",
    lokalizacja: "CH Korona, Krzywoustego 126, 51-421 Wrocław",
    lat: 51.1424467,
    lng: 17.08906829,
  },
  {
    id: 40,
    nazwa: "RNET7382",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Komandorska 53, 53-342 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "ING Bank Śląski, Komandorska 53, 53-342 Wrocław",
    lat: 51.096881,
    lng: 17.027974,
  },
  {
    id: 41,
    nazwa: "RNET7176",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Komandorska 53, 53-342 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "ING Bank Śląski, Komandorska 53, 53-342 Wrocław",
    lat: 51.096881,
    lng: 17.027974,
  },
  {
    id: 42,
    nazwa: "PNET8378",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Bezpieczna 19, 51-114 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Bezpieczna 19, 51-114 Wrocław",
    lat: 51.1407,
    lng: 17.0233,
  },
  {
    id: 43,
    nazwa: "RNET5C38",
    nazwaLokalizacji: "CH Marino ",
    adresLokalizacji: "Paprotna 7, 51-117 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "Disabled",
    lokalizacja: "CH Marino, Paprotna 7, 51-117 Wrocław",
    lat: 51.151915,
    lng: 17.026937,
  },
  // {
  // id: 44,
  //   nazwa: "RNET6789",
  //   nazwaLokalizacji: "BNP Paribas",
  //   adresLokalizacji: "Krawiecka 1F, 50-148 Wrocław",
  //   instytucja: "PlanetBNPP",
  //   moduly: "cashinout",
  //   konfiguracje: [
  //     "BNP Paribas",
  //     "ING Bank Śląski",
  //     "MBank",
  //     "Grupa BPS",
  //     "VeloBank",
  //     "Bank Pocztowy",
  //     "Alior Bank",
  //   ],
  //   typWplaty: "Disabled",
  //   lokalizacja: "BNP Paribas, Krawiecka 1F, 50-148 Wrocław",
  //   lat: 51.10884827,
  //   lng: 17.03820422,
  // },
  {
    id: 45,
    nazwa: "PNET1161",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Przedwiośnie 1, 51-211 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Przedwiośnie 1, 51-211 Wrocław",
    lat: 51.1607,
    lng: 17.1186,
  },
  {
    id: 46,
    nazwa: "SGBA1782",
    nazwaLokalizacji: "Bank",
    adresLokalizacji: "Strachocińska 53A, 55-075 Wrocław",
    instytucja: "SGB SA",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Strachocińska 53A, 55-075 Wrocław",
    lat: 51.109042,
    lng: 17.138724,
  },
  {
    id: 47,
    nazwa: "PNET2139",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Piołunowa 21, 54-530 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Piołunowa 21, 54-530 Wrocław",
    lat: 51.127601,
    lng: 16.880601,
  },
  {
    id: 48,
    nazwa: "RNET6842",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Średzka 18A, 54-001 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "Disabled",
    lokalizacja: "BNP Paribas, Średzka 18A, 54-001 Wrocław",
    lat: 51.145713,
    lng: 16.869243,
  },
  {
    id: 49,
    nazwa: "RNET6843",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Średzka 18A, 54-001 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "Disabled",
    lokalizacja: "BNP Paribas, Średzka 18A, 54-001 Wrocław",
    lat: 51.145713,
    lng: 16.869243,
  },
  {
    id: 50,
    nazwa: "RNET7233",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "pl. Grunwaldzki 22 , 50-363 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "ING Bank Śląski, pl. Grunwaldzki 22 , 50-363 Wrocław",
    lat: 51.112767,
    lng: 17.059108,
  },
  {
    id: 51,
    nazwa: "RNET7234",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "pl. Grunwaldzki 22 , 50-363 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "ING Bank Śląski, pl. Grunwaldzki 22 , 50-363 Wrocław",
    lat: 51.112767,
    lng: 17.059108,
  },
  {
    id: 52,
    nazwa: "RNET7276",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Armii Krajowej 4A, 50-541 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "ING Bank Śląski, Armii Krajowej 4A, 50-541 Wrocław",
    lat: 51.083567,
    lng: 17.037814,
  },
  {
    id: 53,
    nazwa: "RNET7277",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Armii Krajowej 4A, 50-541 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "ING Bank Śląski, Armii Krajowej 4A, 50-541 Wrocław",
    lat: 51.083567,
    lng: 17.037814,
  },
  {
    id: 54,
    nazwa: "RNET7286",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Bema 2, 53-265 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "ING Bank Śląski, Bema 2, 53-265 Wrocław",
    lat: 51.117605,
    lng: 17.041471,
  },
  {
    id: 55,
    nazwa: "RNET7287",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Bema 2, 53-265 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Disabled",
    lokalizacja: "ING Bank Śląski, Bema 2, 53-265 Wrocław",
    lat: 51.117605,
    lng: 17.041471,
  },
  {
    id: 56,
    nazwa: "RNET6920",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Legnicka 56, 54-204 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "Disabled",
    lokalizacja: "BNP Paribas, Legnicka 56, 54-204 Wrocław",
    lat: 51.12056,
    lng: 16.993174,
  },
  {
    id: 57,
    nazwa: "PNET8356",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Konstytucji 3 Maja 3, 50-083 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Konstytucji 3 Maja 3, 50-083 Wrocław",
    lat: 51.0994,
    lng: 17.0401,
  },
  {
    id: 58,
    nazwa: "PNET1265",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Krzycka 45A, 53-019 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Krzycka 45A, 53-019 Wrocław",
    lat: 51.0696,
    lng: 16.9987,
  },
  {
    id: 59,
    nazwa: "RNET6004",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Świeradowska 51/57, 50-559 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "",
    lokalizacja: "BNP Paribas, Świeradowska 51/57, 50-559 Wrocław",
    lat: 51.076281,
    lng: 17.041706,
  },
  {
    id: 60,
    nazwa: "RNET6978",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Kromera 23D, 51-163 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "Disabled",
    lokalizacja: "BNP Paribas, Kromera 23D, 51-163 Wrocław",
    lat: 51.132664,
    lng: 17.065671,
  },
  {
    id: 61,
    nazwa: "RNET5A93",
    nazwaLokalizacji: "oddział mBank",
    adresLokalizacji: "Legnicka 56, 54-204 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "Disabled",
    lokalizacja: "oddział mBank, Legnicka 56, 54-204 Wrocław",
    lat: 51.120717,
    lng: 16.993173,
  },
  {
    id: 62,
    nazwa: "RNET2589",
    nazwaLokalizacji: "Oddział Velo Bank",
    adresLokalizacji: "Gubińska 2c, 54-434 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Oddział Velo Bank, Gubińska 2c, 54-434 Wrocław",
    lat: 51.112302,
    lng: 16.959555,
  },
  {
    id: 63,
    nazwa: "SGBA2297",
    nazwaLokalizacji: "BS Kobierzyce",
    adresLokalizacji: "Poniatowskiego 16-18, 50-326 Wrocław",
    instytucja: "BS Kobierzyce",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "",
    lokalizacja: "Poniatowskiego 16-18, 50-326 Wrocław",
    lat: 51.120776,
    lng: 17.042849,
  },
  {
    id: 64,
    nazwa: "SGBA2074",
    nazwaLokalizacji: "BS Kobierzyce",
    adresLokalizacji: "Chińska 5, 52-116 Wrocław",
    instytucja: "BS Kobierzyce",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "",
    lokalizacja: "Chińska 5, 52-116 Wrocław",
    lat: 51.059677,
    lng: 17.084625,
  },
  {
    id: 65,
    nazwa: "PNET1369",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Kozanowska 2, 54-152 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Kozanowska 2, 54-152 Wrocław",
    lat: 51.132991,
    lng: 16.973602,
  },
  {
    id: 66,
    nazwa: "RNET4254",
    nazwaLokalizacji: "CH Korona",
    adresLokalizacji: "Krzywoustego 126, 51-421 Wrocław",
    instytucja: "PlanetING",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "CH Korona, Krzywoustego 126, 51-421 Wrocław",
    lat: 51.1424467,
    lng: 17.08906829,
  },
  {
    id: 67,
    nazwa: "RNET5M05",
    nazwaLokalizacji: "mBank Pasaż Grunwaldzki",
    adresLokalizacji: "pl. Grunwaldzki 22, 50-363 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "Disabled",
    lokalizacja:
      "Oddział mBanku Pasaz Grun., pl. Grunwaldzki 22, 50-363 Wrocław",
    lat: 51.113033,
    lng: 17.059123,
  },
  {
    id: 68,
    nazwa: "RNET3098",
    nazwaLokalizacji: "CH Carrefour",
    adresLokalizacji: "Graniczna 2A, 54-610 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "CH Carrefour, Graniczna 2A, 54-610 Wrocław",
    lat: 51.1061223,
    lng: 16.9470119,
  },
  {
    id: 69,
    nazwa: "RNETN245",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Olszewskiego 69, 50-121 Wrocław",
    instytucja: "NCRO",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Olszewskiego 69, 50-121 Wrocław",
    lat: 51.1008655,
    lng: 17.1093346,
  },
  {
    id: 70,
    nazwa: "RNETN246",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Olszewskiego 69, 50-121 Wrocław",
    instytucja: "NCRO",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Olszewskiego 69, 50-121 Wrocław",
    lat: 51.1008655,
    lng: 17.1093346,
  },
  {
    id: 71,
    nazwa: "RNET3284",
    nazwaLokalizacji: "Galeria Dominikańska",
    adresLokalizacji: "pl. Dominikański 3, 50-159 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Galeria Dominikańska, pl. Dominikański 3, 50-159 Wrocław",
    lat: 51.108032,
    lng: 17.040753,
  },
  {
    id: 72,
    nazwa: "RNETB001",
    nazwaLokalizacji: "BPS",
    adresLokalizacji: "Krasińskiego 27, 50-449 Wrocław",
    instytucja: "PlanetBPS",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Kaufland",
    lat: 51.10565405,
    lng: 17.04292676,
  },
  {
    id: 73,
    nazwa: "RNET5C73",
    nazwaLokalizacji: "mKiosk",
    adresLokalizacji: "CH Magnolia Park, Legnicka 58, 54-204 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "Disabled",
    lokalizacja: "mKiosk, CH Magnolia Park, Legnicka 58, 54-204 Wrocław",
    lat: 51.119436,
    lng: 16.988923,
  },
  {
    id: 74,
    nazwa: "PNET2181",
    nazwaLokalizacji: "lokal usługowy",
    adresLokalizacji: "Drobnera 12-14 lok.U2, 50-257 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "lokal usługowy, Drobnera 12-14 lok.U2, 50-257 Wrocław",
    lat: 51.117317,
    lng: 17.033946,
  },
  {
    id: 75,
    nazwa: "PNET9457",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Gagarina 19, 54-620 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Gagarina 19, 54-620 Wrocław",
    lat: 51.0973514,
    lng: 16.9362997,
  },
  {
    id: 76,
    nazwa: "PNET1698",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Bacciarellego 56, 51-649 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Bacciarellego 56, 51-649 Wrocław",
    lat: 51.1025193,
    lng: 17.1159577,
  },
  {
    id: 77,
    nazwa: "RNET5D68",
    nazwaLokalizacji: "mKiosk w Carrefour",
    adresLokalizacji: "Graniczna 2a, 54-610 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "Disabled",
    lokalizacja: "mKiosk w Carrefour, Graniczna 2a, 54-610 Wrocław",
    lat: 51.106025,
    lng: 16.946787,
  },
  {
    id: 78,
    nazwa: "PNET2084",
    nazwaLokalizacji: "sklep Lewiatan",
    adresLokalizacji: "Głogowska 6, 53-621 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Sklep Lewiatan, Głogowska 6, 53-621 Wrocław",
    lat: 51.116559,
    lng: 17.002589,
  },
  {
    id: 79,
    nazwa: "PNET1262",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Nowowiejska 48, 50-388 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Nowowiejska 48, 50-388 Wrocław",
    lat: 51.1229,
    lng: 17.0509,
  },
  {
    id: 80,
    nazwa: "RNET5M41",
    nazwaLokalizacji: "oddział mBank",
    adresLokalizacji: "Legnicka 56, 54-204 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Oddział mBank, Legnicka 56, 54-204 Wrocław",
    lat: 51.120717,
    lng: 16.993173,
  },
  {
    id: 81,
    nazwa: "RNET3168",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Królewiecka 68, 54-117 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Królewiecka 68, 54-117 Wrocław",
    lat: 51.15606302,
    lng: 16.92269892,
  },
  {
    id: 82,
    nazwa: "PNET2138",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Popowicka 134, 54-238 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Popowicka 134, 54-238 Wrocław",
    lat: 51.12819444,
    lng: 16.98975,
  },
  {
    id: 83,
    nazwa: "RNET4510",
    nazwaLokalizacji: "Kamienica",
    adresLokalizacji: "Kościuszki 20, 50-026 Wrocław",
    instytucja: "PlanetING",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Kamienica, Kościuszki 20, 50-026 Wrocław",
    lat: 51.102695,
    lng: 17.031108,
  },
  {
    id: 84,
    nazwa: "RNET3188",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Kiełczowska 137A, 51-315 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Kiełczowska 137A, 51-315 Wrocław",
    lat: 51.145,
    lng: 17.1368,
  },
  {
    id: 85,
    nazwa: "RNET3199",
    nazwaLokalizacji: "Centrum Handlowe Krzyki",
    adresLokalizacji: "Wawrzyniaka 2, 53-022 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Centrum Handlowe Krzyki, Wawrzyniaka 2, 53-022 Wrocław",
    lat: 51.074958,
    lng: 17.00451,
  },
  {
    id: 86,
    nazwa: "PNET2961",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Pszczelarska 9, 52-210 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Pszczelarska 9, 52-210 Wrocław",
    lat: 51.05774,
    lng: 17.02251,
  },
  {
    id: 87,
    nazwa: "RNET4531",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Parafialna 21, 52-233 Wrocław",
    instytucja: "PlanetING",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Biedronka, Parafialna 21, 52-233 Wrocław",
    lat: 51.0629,
    lng: 17.0329,
  },
  {
    id: 88,
    nazwa: "RNET3222",
    nazwaLokalizacji: "CH Magnolia Park",
    adresLokalizacji: "Legnicka 58, 54-204 Wroclaw dolnośląskie",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "CH Magnolia Park, Legnicka 58, 54-204 Wroclaw dolnośląskie",
    lat: 51.118754,
    lng: 16.989575,
  },
  {
    id: 89,
    nazwa: "PNET2829",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Żernicka 207, 54-510 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Żernicka 207, 54-510 Wrocław",
    lat: 51.1232,
    lng: 16.9257,
  },
  {
    id: 90,
    nazwa: "RNET6116",
    nazwaLokalizacji: "BNP Paribas",
    adresLokalizacji: "Swobodna 3, 50-541 Wrocław",
    instytucja: "PlanetBNPP",
    moduly: "cashinout",
    konfiguracje: [
      "BNP Paribas",
      "ING Bank Śląski",
      "MBank",
      "Grupa BPS",
      "VeloBank",
      "Bank Pocztowy",
      "Alior Bank",
    ],
    typWplaty: "Disabled",
    lokalizacja: "BNP Paribas, Swobodna 3, 50-541 Wrocław",
    lat: 51.0981891,
    lng: 17.0323355,
  },
  {
    id: 91,
    nazwa: "PNET8706",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Krzywoustego 40, 51-166 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Krzywoustego 40, 51-166 Wrocław",
    lat: 51.1382425,
    lng: 17.07431816,
  },
  {
    id: 92,
    nazwa: "PNET1283",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Sarnia 1, 52-129 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Sarnia 1, 52-129 Wrocław",
    lat: 51.04993,
    lng: 17.0585462,
  },
  {
    id: 93,
    nazwa: "PNET1220",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Zielińskiego 61A, 53-533 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Biedronka, Zielińskiego 61A, 53-533 Wrocław",
    lat: 51.0979,
    lng: 17.0189,
  },
  {
    id: 94,
    nazwa: "PNET2256",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Awicenny 51, 54-611 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "",
    lokalizacja: "Biedronka, Awicenny 51, 54-611 Wrocław",
    lat: 51.080996,
    lng: 16.955974,
  },
  {
    id: 95,
    nazwa: "RNET5F38",
    nazwaLokalizacji: "Centrum Handlowe Gaj ",
    adresLokalizacji: "Świeradowska 70, 50-559 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Centrum Handlowe Gaj , Świeradowska 70, 50-559 Wrocław",
    lat: 51.077341,
    lng: 17.047832,
  },
  {
    id: 96,
    nazwa: "PNET2758",
    nazwaLokalizacji: "Przy sklepie z warzywami ",
    adresLokalizacji: "Wojanowska 2a, 54-050 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "Przy sklepie z warzywami , Wojanowska 2a, 54-050 Wrocław",
    lat: 51.153493,
    lng: 16.892494,
  },
  {
    id: 97,
    nazwa: "PNET2305",
    nazwaLokalizacji: "przy kamienicy",
    adresLokalizacji: "Dubois 12, 50-216 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashout",
    konfiguracje: [],
    typWplaty: "Disabled",
    lokalizacja: "przy kamienicy, Dubois 12, 50-216 Wrocław",
    lat: 51.1172416,
    lng: 17.0321982,
  },
  {
    id: 98,
    nazwa: "RNET4551",
    nazwaLokalizacji: "CH Magnolia Park",
    adresLokalizacji: "Legnicka 58, 54-204 Wroclaw dolnośląskie",
    instytucja: "PlanetING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "CH Magnolia Park, Legnicka 58, 54-204 Wroclaw dolnośląskie",
    lat: 51.118754,
    lng: 16.989575,
  },
  {
    id: 99,
    nazwa: "RNET3626",
    nazwaLokalizacji: "Centrum Handlowe Arena",
    adresLokalizacji: "Komandorska 66, 53-342 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Centrum Handlowe Arena, Komandorska 66, 53-342 Wrocław",
    lat: 51.094936,
    lng: 17.028339,
  },
  {
    id: 100,
    nazwa: "RNET3699",
    nazwaLokalizacji: "Centrum Handlowe TGG",
    adresLokalizacji: "Słubicka 18, 53-615 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Centrum Handlowe TGG, Słubicka 18, 53-615 Wrocław",
    lat: 51.117905,
    lng: 17.000571,
  },
  {
    id: 101,
    nazwa: "RNET3694",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Afgańska 3, 52-117 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "52941",
    lokalizacja: "Biedronka, Afgańska 3, 52-117 Wrocław",
    lat: 51.0624,
    lng: 17.0825,
  },
  // {
  // id: 102,
  //   nazwa: "RNETA001",
  //   nazwaLokalizacji: "Credit Agricole",
  //   adresLokalizacji: "Krawiecka 1e, 50-148 Wrocław",
  //   instytucja: "CreditAgricole",
  //   moduly: "cashout",
  //   konfiguracje: [
  //     "Credit Agricole",
  //     "Alior Bank",
  //     "Grupa BPS",
  //     "VeloBank",
  //     "MBank",
  //     "ING Bank Śląski",
  //     "BNP Paribas",
  //     "Bank Pocztowy",
  //   ],
  //   typWplaty: "Cash In FlexDMS",
  //   lokalizacja: "Credit Agricole, Krawiecka 1e, 50-148 Wrocław",
  //   lat: 51.10824664350202,
  //   lng: 17.038144571935334,
  // },
  {
    id: 103,
    nazwa: "RNET5M57",
    nazwaLokalizacji: "Oddział mBank",
    adresLokalizacji: "pl. Jana Pawła II 9, 50-136 Wrocław",
    instytucja: "mBank",
    moduly: "cashout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "BNP Paribas",
      "Bank Pocztowy",
      "ING Bank Śląski",
    ],
    typWplaty: "Disabled",
    lokalizacja: "Oddział mBank, pl. Jana Pawła II 9, 50-136 Wrocław",
    lat: 51.111536638331515,
    lng: 17.0233512257125,
  },
  {
    id: 104,
    nazwa: "RNETA088",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "al. Armii Krajowej 4C, 50-541 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, al. Armii Krajowej 4C, 50-541 Wrocław",
    lat: 51.083941,
    lng: 17.037925,
  },
  {
    id: 105,
    nazwa: "RNETA089",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "al. Armii Krajowej 4C, 50-541 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, al. Armii Krajowej 4C, 50-541 Wrocław",
    lat: 51.083941,
    lng: 17.037925,
  },
  {
    id: 106,
    nazwa: "RNET3650",
    nazwaLokalizacji: "przy barze Trzy Stoliki",
    adresLokalizacji: "Hermanowska 59B, 54-314 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "przy barze Trzy Stoliki, Hermanowska 59B, 54-314 Wrocław",
    lat: 51.124204204425,
    lng: 16.950029556634,
  },
  {
    id: 107,
    nazwa: "RNETA179",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Legnicka 48, 54-202 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Legnicka 48, 54-202 Wrocław",
    lat: 51.11781061094989,
    lng: 16.996579973433853,
  },
  {
    id: 108,
    nazwa: "RNETA180",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Legnicka 48, 54-202 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Legnicka 48, 54-202 Wrocław",
    lat: 51.11781061094989,
    lng: 16.996579973433853,
  },
  {
    id: 109,
    nazwa: "RNETA094",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Swobodna 1, 50-088 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Swobodna 1, 50-088 Wrocław",
    lat: 51.097837,
    lng: 17.03251,
  },
  {
    id: 110,
    nazwa: "RNETA095",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Swobodna 1, 50-088 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Swobodna 1, 50-088 Wrocław",
    lat: 51.097837,
    lng: 17.03251,
  },
  {
    id: 111,
    nazwa: "RNETA086",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "pl. Powstańców Śląskich 1, 53-329 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, pl. Powstańców Śląskich 1, 53-329 Wrocław",
    lat: 51.091529,
    lng: 17.016832,
  },
  // {
  // id: 112,
  // 	nazwa: 'RNETA087',
  // 	nazwaLokalizacji: 'Credit Agricole',
  // 	adresLokalizacji: 'pl. Powstańców Śląskich 1, 53-329 Wrocław',
  // 	instytucja: 'CreditAgricole',
  // 	moduly: 'cashout',
  // 	konfiguracje: [
  // 		'Credit Agricole',
  // 		'Alior Bank',
  // 		'Grupa BPS',
  // 		'VeloBank',
  // 		'MBank',
  // 		'ING Bank Śląski',
  // 		'BNP Paribas',
  // 		'Bank Pocztowy',
  // 	],
  // 	typWplaty: 'Cash In FlexDMS',
  // 	lokalizacja: 'Credit Agricole, pl. Powstańców Śląskich 1, 53-329 Wrocław',
  // 	lat: 51.091529,
  // 	lng: 17.016832,
  // },
  {
    id: 113,
    nazwa: "RNETA092",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Strzegomska 206/208, 54-432 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Strzegomska 206/208, 54-432 Wrocław",
    lat: 51.111386,
    lng: 16.959597,
  },
  {
    id: 114,
    nazwa: "RNETA093",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Strzegomska 206/208, 54-432 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Strzegomska 206/208, 54-432 Wrocław",
    lat: 51.111386,
    lng: 16.959597,
  },
  {
    id: 115,
    nazwa: "RNET3348",
    nazwaLokalizacji: "przy sklepie Lewiatan",
    adresLokalizacji: "Złotnicka 17, 54-029 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "przy sklepie Lewiatan, Złotnicka 17, 54-029 Wrocław",
    lat: 51.141174,
    lng: 16.886774,
  },
  {
    id: 116,
    nazwa: "RNETA309",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Krawiecka. 1e, 50-148 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Krawiecka. 1e, 50-148 Wrocław",
    lat: 51.10824664350202,
    lng: 17.038144571935334,
  },
  {
    id: 117,
    nazwa: "RNETA101",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Jedności Narodowej 71, 50-262 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Jedności Narodowej 71, 50-262 Wrocław",
    lat: 51.120566,
    lng: 17.040782,
  },
  {
    id: 118,
    nazwa: "RNETA102",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Jedności Narodowej 71, 50-262 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Jedności Narodowej 71, 50-262 Wrocław",
    lat: 51.120566,
    lng: 17.040782,
  },
  {
    id: 119,
    nazwa: "RNET3370",
    nazwaLokalizacji: "Biedronka",
    adresLokalizacji: "Bystrzycka 55, 50-159 Wrocław",
    instytucja: "PlanetCash",
    moduly: "cashinout",
    konfiguracje: [
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Biedronka, Bystrzycka 55, 50-159 Wrocław",
    lat: 51.11916587,
    lng: 16.97915003,
  },
  {
    id: 120,
    nazwa: "RNET7417",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Lotnicza 12, 54-155 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "ING Bank Śląski, Lotnicza 12, 54-155 Wrocław",
    lat: 51.12692303466769,
    lng: 16.978270393253485,
  },
  {
    id: 121,
    nazwa: "RNETA313",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Mikołaja Reja 2D, 50-354 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Mikołaja Reja 2D, 50-354 Wrocław",
    lat: 51.112796,
    lng: 17.056454,
  },
  {
    id: 122,
    nazwa: "RNETA310",
    nazwaLokalizacji: "Credit Agricole",
    adresLokalizacji: "Józefa Piłsudskiego 60, 50-033 Wrocław",
    instytucja: "CreditAgricole",
    moduly: "cashout",
    konfiguracje: [
      "Credit Agricole",
      "Alior Bank",
      "Grupa BPS",
      "VeloBank",
      "MBank",
      "ING Bank Śląski",
      "BNP Paribas",
      "Bank Pocztowy",
    ],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "Credit Agricole, Józefa Piłsudskiego 60, 50-033 Wrocław",
    lat: 51.101438,
    lng: 17.029771,
  },
  {
    id: 123,
    nazwa: "RNET7418",
    nazwaLokalizacji: "ING Bank Śląski",
    adresLokalizacji: "Lotnicza 12, 54-155 Wrocław",
    instytucja: "ING",
    moduly: "cashinout",
    konfiguracje: ["ING Bank Śląski"],
    typWplaty: "Cash In FlexDMS",
    lokalizacja: "ING Bank Śląski, Lotnicza 12, 54-155 Wrocław",
    lat: 51.12692303466769,
    lng: 16.978270393253485,
  },
];
